# Generated by Django 3.1.2 on 2020-12-13 16:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_region_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Название прибора дожно состоять хотя бы с 3 символов')], verbose_name='Название')),
                ('power', models.DecimalField(decimal_places=3, default=None, max_digits=15)),
                ('time_of_work', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(23, 59))),
                ('days', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='days_devices', to='electricity.dayofweek')),
                ('device', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='electricity.electricaldevices')),
            ],
        ),
        migrations.AddField(
            model_name='electricaldevices',
            name='switch_off',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='switch_off_types', to='electricity.switchtype'),
        ),
        migrations.AddField(
            model_name='electricaldevices',
            name='switch_on',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='switch_on_types', to='electricity.switchtype'),
        ),
    ]
