# Generated by Django 3.1.2 on 2020-10-12 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrology',
            name='begin_day',
        ),
        migrations.RemoveField(
            model_name='metrology',
            name='end_day',
        ),
        migrations.AddField(
            model_name='metrology',
            name='begin_date',
            field=models.DateField(default=datetime.date(2012, 1, 1)),
        ),
        migrations.AddField(
            model_name='metrology',
            name='end_date',
            field=models.DateField(default=datetime.date(2012, 12, 31)),
        ),
    ]
