# Generated by Django 3.1.2 on 2020-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrology', '0002_auto_20201012_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrologydata',
            name='wind_speed',
            field=models.IntegerField(default=0),
        ),
    ]
