# Generated by Django 3.1.2 on 2020-10-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrology', '0003_metrologydata_wind_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrology',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
