# Generated by Django 3.1.2 on 2020-10-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrology', '0004_metrology_is_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('metrology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrology.metrology')),
            ],
        ),
    ]
