# Generated by Django 3.1.2 on 2020-11-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('metrology', '0005_solardata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrologydata',
            name='metrology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='metrology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.DeleteModel(
            name='Metrology',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
