# Generated by Django 3.1.2 on 2020-11-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_region_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_loss', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('area', models.DecimalField(decimal_places=1, default=None, max_digits=6)),
                ('residents', models.PositiveIntegerField(default=None)),
                ('water_start_temperature', models.DecimalField(decimal_places=1, default=15, max_digits=6)),
                ('water_end_temperature', models.DecimalField(decimal_places=1, default=85, max_digits=6)),
                ('water_shower_temperature', models.DecimalField(decimal_places=1, default=40, max_digits=6)),
                ('shower_number', models.PositiveIntegerField(default=None)),
                ('water_bath_temperature', models.DecimalField(decimal_places=1, default=40, max_digits=6)),
                ('bath_number', models.PositiveIntegerField(default=None)),
                ('heating_duration', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4)),
                ('heater_power', models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=15)),
                ('expected_air_temperature', models.DecimalField(decimal_places=1, default=20, max_digits=6)),
                ('shower_water_volume', models.DecimalField(decimal_places=8, default=None, max_digits=15, null=True)),
                ('bath_water_volume', models.DecimalField(decimal_places=8, default=None, max_digits=15, null=True)),
                ('total_water_volume', models.DecimalField(decimal_places=8, default=None, max_digits=15, null=True)),
                ('q_shower_normal', models.DecimalField(blank=True, decimal_places=1, default=150, max_digits=10)),
                ('q_bath_normal', models.DecimalField(blank=True, decimal_places=1, default=75, max_digits=10)),
                ('q_shower', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10)),
                ('q_bath', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10)),
                ('energy', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
