# Generated by Django 3.1.2 on 2020-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='q_bath',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='q_shower',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
    ]
