# Generated by Django 3.1.2 on 2020-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20201123_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='energy',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
    ]
