# Generated by Django 3.1.2 on 2020-11-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20201123_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='heater_power',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=15),
        ),
    ]
