# Generated by Django 3.1.2 on 2020-11-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20201123_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='coal_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='electrical_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='gaz_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='pellets_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='wood_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
